# Generated by Django 4.2.24 on 2025-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_meetingrequest_facultypersonalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=10),
        ),
    ]
