# Generated by Django 4.2.24 on 2026-02-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0006_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Courses",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="bookedunit",
            options={
                "ordering": ["course__name", "lecturer"],
                "verbose_name_plural": "Booked units",
            },
        ),
        migrations.RemoveField(
            model_name="bookedunit",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="lecturehall",
            name="image",
        ),
        migrations.AddField(
            model_name="bookedunit",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campus.course",
            ),
        ),
    ]
