# Generated by Django 4.2.24 on 2026-02-09 19:58

from django.db import migrations
import uuid


def create_default_course_and_update_bookedunits(apps, schema_editor):
    Course = apps.get_model('campus', 'Course')
    BookedUnit = apps.get_model('campus', 'BookedUnit')

    # Create a default Course if it doesn't exist
    # Using a deterministic ID for consistency, or generate a new one
    try:
        default_course = Course.objects.get(code='UNASSIGNED')
    except Course.DoesNotExist:
        default_course = Course.objects.create(
            id=str(uuid.uuid4()), # Generate a unique ID
            name='Unassigned Course',
            code='UNASSIGNED',
            description='Default course for units created before course migration.'
        )

    # Update existing BookedUnit objects that have no course assigned
    for booked_unit in BookedUnit.objects.filter(course__isnull=True):
        booked_unit.course = default_course
        booked_unit.save()


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0007_course_alter_bookedunit_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_course_and_update_bookedunits),
    ]