# Generated by Django 4.2.24 on 2026-02-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0008_auto_20260209_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedunit",
            name="course",
            field=models.ForeignKey(
                default="46a15f51-0eff-4ab9-8710-881f2746b0bb",
                on_delete=django.db.models.deletion.CASCADE,
                to="campus.course",
            ),
        ),
    ]
