# Generated by Django 4.2.24 on 2026-02-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0009_alter_bookedunit_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedunit",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campus.course"
            ),
        ),
    ]
