# Generated by Django 4.2.24 on 2026-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0010_alter_bookedunit_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultypersonalevent",
            name="sent_reminders",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of sent reminder times, e.g., '60min,15min'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="sent_reminders",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of sent reminder times, e.g., '60min,15min'",
                max_length=100,
            ),
        ),
    ]
