# Generated by Django 4.2.24 on 2026-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0011_facultypersonalevent_sent_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultypersonalevent",
            name="is_signed_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultypersonalevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="meetingrequest",
            name="is_signed_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="is_signed_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bookedunit",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="facultypersonalevent",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lecturehall",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="meetingrequest",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="meetingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("modified", "Modified"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registeredunit",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpersonalevent",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
