# Generated by Django 4.2.24 on 2026-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0012_facultypersonalevent_is_signed_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultypersonalevent",
            name="parent_event_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facultypersonalevent",
            name="recurrence_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultypersonalevent",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultypersonalevent",
            name="recurrence_end_type",
            field=models.CharField(
                blank=True,
                choices=[("count", "By Count"), ("date", "By Date")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="facultypersonalevent",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="parent_event_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="recurrence_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="recurrence_end_type",
            field=models.CharField(
                blank=True,
                choices=[("count", "By Count"), ("date", "By Date")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="parent_event_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="recurrence_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="recurrence_end_type",
            field=models.CharField(
                blank=True,
                choices=[("count", "By Count"), ("date", "By Date")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
