# Generated by Django 4.2.24 on 2026-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0013_facultypersonalevent_parent_event_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Holidays / Exam Weeks",
                "ordering": ["start_date"],
            },
        ),
        migrations.AlterField(
            model_name="facultypersonalevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("exempt", "Exempt"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("exempt", "Exempt"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentpersonalevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("exempt", "Exempt"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
