# Generated by Django 4.2.24 on 2026-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0014_holiday_and_exempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrequest",
            name="lecturer_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks added by the lecturer when approving or rejecting the request.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meetingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("modified", "Modified"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
