# Generated by Django 4.2.24 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0015_meeting_request_remarks_and_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultypersonalevent",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="studentpersonalevent",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=6,
            ),
        ),
    ]
