# Generated by Django 4.2.24 on 2025-11-10 20:55

from django.db import migrations


def update_hod_to_admin(apps, schema_editor):
    """
    Find all Faculty members with the position 'HOD' and update it to 'Admin'.
    """
    Faculty = apps.get_model('accounts', 'Faculty')
    Faculty.objects.filter(position='HOD').update(position='Admin')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_hod_to_admin),
    ]
