# Generated by Django 4.2.24 on 2025-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251111_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_preference',
            field=models.CharField(choices=[('instant', '即时提醒 (Instant)'), ('15min', '提前15分钟 (15 minutes before)'), ('30min', '提前30分钟 (30 minutes before)')], default='instant', max_length=10, verbose_name='提醒偏好'),
        ),
        migrations.AddField(
            model_name='user',
            name='repeat_reminders',
            field=models.BooleanField(default=False, verbose_name='重复提醒'),
        ),
    ]
