# Generated by Django 4.2.24 on 2025-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251111_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_preference',
            field=models.CharField(choices=[('instant', 'Instant'), ('15min', '15 minutes before'), ('30min', '30 minutes before')], default='instant', max_length=10, verbose_name='Reminder Preference'),
        ),
        migrations.AddField(
            model_name='user',
            name='repeat_reminders',
            field=models.BooleanField(default=False, verbose_name='Repeat Reminders'),
        ),
    ]
