# Generated by Django 4.2.24 on 2025-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reminder_preference_user_repeat_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_method',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=10, verbose_name='Notification Method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reminder_preference',
            field=models.CharField(choices=[('instant', 'Instant'), ('15min', '15 minutes before'), ('30min', '30 minutes before')], default='instant', max_length=10, verbose_name='Reminder Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='repeat_reminders',
            field=models.BooleanField(default=False, verbose_name='Repeat Reminders'),
        ),
    ]
