# Generated by Django 4.2.24 on 2025-11-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_notification_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repeat_reminders',
        ),
        migrations.AlterField(
            model_name='user',
            name='reminder_preference',
            field=models.CharField(default='15min', help_text='Select one or more reminder times.', max_length=100, verbose_name='Reminder Times'),
        ),
    ]
